name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: GitSSHGroup
  - group: ApiKeys
  - group: OctoDefault
  - name: buildConfiguration
    value: 'Release'
  - name: buildPlatform
    value: 'any cpu'    
  - name: solutionFile
    value: 'Octo.MeshAdapter.sln'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}

stages:
  - stage: Build
    jobs:
      - job: linux
        displayName: Docker build
        pool:
          name: Gerald-Local-Linux
        steps:
          - template: update-build-number.yml
          - checkout: self
            clean: true
            submodules: recursive
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: '$(SSHKnownHosts)'
              sshPublicKey: '$(SSHPublicKey)'
              sshPassphrase: '$(SSHPassphrase)'
              sshKeySecureFile: '$(SSHPrivateKeyFile)'
          - template: set-version.yml
          - template: download-ca.yml
          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: 'build'
              projects: $(SolutionFile)
              arguments: '--configuration $(BuildConfiguration) -p:OctoNugetPrivateServer=$(NugetPrivateServer)'
              publishWebProjects: false
              zipAfterPublish: false
              modifyOutputPath: false
          - task: DotNetCoreCLI@2
            displayName: 'Test'
            inputs:
              command: 'test'
              projects: |
                '**/*Tests.csproj'
                !'**/*SystemTests.csproj'
              testRunTitle: 'CI'
          - task: CopyFiles@2
            displayName: 'Copy Files from **/*.nupkg to $(build.artifactstagingdirectory)'
            inputs:
              SourceFolder: $(Build.SourcesDirectory)
              Contents: |
                bin/**/*.nupkg
                bin/**/documentation/**/*.*
              TargetFolder: $(build.artifactstagingdirectory)
          - task: PowerShell@2
            displayName: 'Create versioninfo file'
            inputs:
              targetType: 'inline'
              script: |
                New-Item $(build.artifactstagingdirectory)/versioninfo.txt
                Set-Content $(build.artifactstagingdirectory)/versioninfo.txt $(Build.BuildNumber)
          - template: build-and-push-docker-image.yml
            parameters:
              Repository: meshmakers/octo-mesh-adapter
              Dockerfile: src/MeshAdapter/Dockerfile
              IsRelease: ${{ variables.isRelease }}
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: local'
            inputs:
              ArtifactName: local
          - task: DotNetCoreCLI@2
            displayName: Push Nuget Package
            condition: eq(variables.isRelease, true)
            inputs:
              command: custom
              custom: nuget
              arguments: >
                push $(Build.ArtifactStagingDirectory)/**/*.nupkg
                -s https://api.nuget.org/v3/index.json
                -k $(NuGetApiKey) 

